safe:        false
port: 4000
baseurl:    /
url: http://drab-makyo.com
name: Drab Makyo - Matthew Scott
description: Writing (on various topics) from Matthew Scott

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
markdown:    kramdown
highlighter: pygments
permalink:   pretty
paginate:    5
